/* Service worker for {{ brand.slug }} — generated by views/field.py.
   Shell = pages + css + js + logo. API calls are never cached. */
const CACHE = {{ cache_name | tojson }};
const SHELL = {{ shell | tojson }};
const SCOPE = {{ form_url | tojson }};

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(keys => Promise.all(
      keys.filter(k => k.startsWith('field-{{ brand.slug }}-') && k !== CACHE).map(k => caches.delete(k))
    )).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;                       // POSTs go straight to network
  const url = new URL(req.url);
  if (url.pathname.startsWith(SCOPE + 'api/')) return;     // never serve API from cache

  // Pages: network first, cache fallback. Static: cache first, refresh in background.
  const isPage = req.mode === 'navigate';
  e.respondWith(
    isPage
      ? fetch(req).then(r => { const c = r.clone(); caches.open(CACHE).then(x => x.put(req, c)); return r; })
                  .catch(() => caches.match(req, { ignoreSearch: true }).then(r => r || caches.match(SCOPE)))
      : caches.match(req).then(hit => {
          const net = fetch(req).then(r => { if (r.ok) { const c = r.clone(); caches.open(CACHE).then(x => x.put(req, c)); } return r; }).catch(() => hit);
          return hit || net;
        })
  );
});
