"""
Lightweight per-site PDF report.

A trimmed reimplementation of the DAILY REPORT layout from
bulk_summary_generator.py (the agency box, summary-statistics table, and the
detailed records table) — same ReportLab styling, ~150 lines instead of 2300,
no pandas / GCS / menus. Takes already-normalized records from site_api.

build_report(...) returns PDF bytes; the view streams them.
"""
from __future__ import annotations

import io
from datetime import datetime
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

# Detail columns (sum ≈ 802 pt usable on landscape A4 with 20pt margins).
_HEADERS = ["S.NO", "DATE", "TIME", "TICKET", "VEHICLE NO", "MATERIAL",
            "First Wt", "IN", "Second Wt", "OUT", "Net Wt"]
_COL_WIDTHS = [34, 64, 52, 60, 78, 96, 64, 52, 64, 52, 64]


def _styles() -> dict:
    return {
        "summary_header": ParagraphStyle(
            "sh", fontSize=12, alignment=TA_CENTER, fontName="Helvetica-Bold",
            textColor=colors.darkblue, spaceAfter=8, spaceBefore=12),
        "sub": ParagraphStyle(
            "sub", fontSize=11, alignment=TA_CENTER, fontName="Helvetica",
            textColor=colors.black, spaceAfter=6),
        "attr": ParagraphStyle(
            "attr", fontSize=10, alignment=TA_CENTER, fontName="Helvetica",
            textColor=colors.darkgrey, spaceAfter=4),
    }


def _kg(v) -> str:
    try:
        return f"{float(v):.1f} kg"
    except (TypeError, ValueError):
        return "0.0 kg"


def build_report(site_name: str, agency_name: str, filters: dict,
                 records: list[dict], summary: Optional[dict] = None) -> bytes:
    st = _styles()
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=landscape(A4),
                            rightMargin=20, leftMargin=20,
                            topMargin=30, bottomMargin=30)
    el: list = []

    # ---- Agency box ----
    agency_tbl = Table([[agency_name or "Agency"]], colWidths=[sum(_COL_WIDTHS)])
    agency_tbl.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 2, colors.black),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 16),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    el.append(agency_tbl)

    # ---- Title / meta ----
    period = _period_label(filters)
    el.append(Paragraph(f"<b>SITE REPORT — {site_name}</b>", st["summary_header"]))
    el.append(Paragraph(f"<b>Period: {period}</b>", st["sub"]))
    if filters.get("material"):
        el.append(Paragraph(f"<b>Material Type: {filters['material']}</b>", st["sub"]))
    if filters.get("vehicle"):
        el.append(Paragraph(f"<b>Vehicle: {filters['vehicle']}</b>", st["sub"]))
    ts = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
    el.append(Paragraph(f"<b>Report Generated:</b> {ts}", st["sub"]))
    el.append(Spacer(1, 12))

    # ---- Summary statistics ----
    trips = len(records)
    total_kg = sum(r.get("net_weight_kg", 0.0) for r in records)
    total_mt = total_kg / 1000.0
    avg_kg = (total_kg / trips) if trips else 0.0

    el.append(Paragraph("SUMMARY STATISTICS", st["summary_header"]))
    summary_tbl = Table([
        ["Statistic", "Value"],
        ["Site", site_name],
        ["Period", period],
        ["Material Type", filters.get("material") or "All"],
        ["Vehicle", filters.get("vehicle") or "All"],
        ["Total Number of Trips", f"{trips:,}"],
        ["Total Net Weight", f"{total_mt:.3f} MT ({total_kg:.2f} kg)"],
        ["Average Weight per Trip", f"{avg_kg:.2f} kg"],
    ], colWidths=[250, 350])
    summary_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 11),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.beige]),
    ]))
    el.append(summary_tbl)

    el.append(Paragraph("─" * 40, st["attr"]))
    el.append(Paragraph(
        f"Report generated by Swaccha Andhra Monitor by Advitia Labs at {ts}",
        st["attr"]))
    el.append(Spacer(1, 12))

    # ---- Detailed records ----
    el.append(Paragraph("DETAILED RECORDS", st["summary_header"]))
    rows = [_HEADERS]
    for i, r in enumerate(records, 1):
        rows.append([
            str(i), r.get("date", ""), r.get("time", ""),
            r.get("ticket_no", ""), r.get("vehicle_no", ""),
            r.get("material_type", ""),
            _kg(r.get("first_weight_kg")), r.get("first_time", ""),
            _kg(r.get("second_weight_kg")), r.get("second_time", ""),
            _kg(r.get("net_weight_kg")),
        ])
    detail = Table(rows, repeatRows=1, colWidths=_COL_WIDTHS)
    detail.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.beige]),
    ]))
    el.append(detail)

    final = Table([[f"TOTAL: {trips} trips | {total_mt:.3f} MT"]],
                  colWidths=[sum(_COL_WIDTHS)])
    final.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.lightgreen),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    el.append(final)

    doc.build(el)
    return buf.getvalue()


def _period_label(filters: dict) -> str:
    s, e = filters.get("start"), filters.get("end")
    if s and e:
        return s if s == e else f"{s} to {e}"
    return s or e or "All dates"